#!/usr/bin/python

class CREQ:
    BASE = "CREQ."

    NOTIFY_UPDATE = BASE + "NOTIFY_UPDATE"
    NOTIFY_ANALYZE = BASE + "NOTIFY_ANALYZE"
    ANALYZE_APP = BASE + "ANALYZE_APP"
    ANALYZE_DIR = BASE + "ANALYZE_DIR"
    REPORT_STATUS = BASE + "REPORT_STATUS"

class WREQ:
    BASE = "WREQ."

    REQ_FILE = BASE + "REQ_FILE"
    REP_FILE = BASE + "REP_FILE"

    REQ_ANALYSIS = BASE + "REQ_ANALYSIS"
    REP_ANALYSIS = BASE + "REP_ANALYSIS"
    FIN_ANALYSIS = BASE + "FIN_ANALYSIS"

    STATUS = BASE + "STATUS"

    DONE     = BASE + "DONE"

class SPUB:
    BASE = "SPUB."

    NOTIFY_UPDATE = BASE + "NOTIFY_UPDATE"
    ANALYZE_APP = BASE + "ANALYZE_APP"
    UPDATE_STATUS = BASE + "UPDATE_STATUS"

